field.field.ps_division.ps_division.*.yml:
  type: config_entity
  label: 'Field'

field.storage.ps_division.*.yml:
  type: config_entity
  label: 'Field storage'

ps_division.settings:
  type: config_object
  label: 'Division settings'
  mapping:
    allow_unknown_parent:
      type: boolean
      label: 'Allow unknown parent entity IDs'
    auto_create_on_unknown:
      type: boolean
      label: 'Auto-create inactive division on unknown parent'
